/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue",
  ],
  theme: {
    screens: {
      xs: "320px",
      sm: "425px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xxl: "1440px"
    },
    colors: {
      primary1: "var(--color-primary1)",
      primary2: "var(--color-primary2)",
      primaryLight: "var(--color-primaryLight)",
      secondary: "var(--color-secondary)",
      tertiary: "var(--color-tertiary1)",
      tertiaryLight: "var(--color-tertiary2)",
      tertiaryLight2: "var(--color-tertiary3)",
      lightBg: "var(--color-lightBg)",
      gray: "var(--color-gray)",
      darkGray: "var(--color-darkGray)",
      lightGray: "var(--color-lightGray)",

      formBg: "var(--color-formBg)",
      accent: "var(--color-accent)",
      accentLight: "var(--color-accentLight)",
      transparent: "var(--color-transparent)",
      light: "var(--color-light)",
      dark: "var(--color-dark)",
      white: "var(--color-white)",
      heading: "var(--color-heading)",
      subheading: "var(--color-subheading)",
      body: "var(--color-body)",
      error: "var(--color-error)",
      success: "var(--color-success)",
      info: "var(--color-info)",
      warning: "var(--color-warning)",
      red: "var(--color-red)",
    },
    extend: {},
  },
};
